### ISSUE TITLE
Python code missing

### ISSUE THREAD

**Issue by brontide** [fxkr/unifi-protocol-reverse-engineering#1]
I know this is mostly abandoned but I'm exploring the Unifi ecosystem and seeing the code might assist with some of the work I've been doing.  If not could you at least write a little more detail about the encryption and decryption of the packets and where the keys are stored.

**Comment by fxkr** [comment]
The keys are stored in a MongoDB in the controller. You can use a standard MongoDB client to connect to it. I don't know where exactly anymore, but with a graphical client it's easy to find.

The key in Mongo is just hex encoded. The encryption is AES CBC with CMS padding, ignoring any errors when removing the padding. Depending on a flag in the unencrypted binary part before the encrypted blob, the plaintext is gzipped. Depending on a flag in the unencrypted binary part the plaintext is then another easy binary format (v0) or json (v1).

I'll send you an email with some scripts in whatever state I have them.

Hope it helps!

**Comment by brontide** [comment]
Thanks again.  In the api ( api/s/{sitename}/stat/device ) I see two identical 16byte keys ( x_authkey, x_inform_authkey ) for each unifi device I'll capture some informs and see if they do the trick.
